=== Ahddry/PiscineWeb2022/XML/template.dtd
<!ELEMENT cv (etatCivil,diplomes,experiences)>

<!ELEMENT etatCivil (nom , prenom, age)>

<!ELEMENT diplomes (diplome+)>
<!ELEMENT diplome (libelle , annee, institution)>

<!ELEMENT experiences (experience+)>
<!ELEMENT experience (debut , fin, entreprise, poste)>


<!ELEMENT nom (#PCDATA )>
<!ELEMENT prenom (#PCDATA )>
<!ELEMENT age (#PCDATA )>

<!ELEMENT libelle (#PCDATA )>
<!ELEMENT annee (#PCDATA )>
<!ELEMENT institution (#PCDATA )>

<!ELEMENT debut (#PCDATA )>
<!ELEMENT fin (#PCDATA )>
<!ELEMENT entreprise (#PCDATA )>
<!ELEMENT poste (#PCDATA )>

=== Ahddry/PiscineWeb2022/XML/12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Liguili</nom>
        <prenom>Guy</prenom>
        <age>1984</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>1998</annee>
            <institution>Université Strasbourg</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2015</debut>
            <fin>2021</fin>
            <entreprise>Médecin-Urgentiste</entreprise>
            <poste>CHRU Strarbourg</poste>
        </experience>
        <experience>
            <debut>2021</debut>
            <fin>Présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Généraliste</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Téziste</nom>
        <prenom>Agnès</prenom>
        <age>1982</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en Médecine</libelle>
            <annee>2002</annee>
            <institution>Université Pierre et Maire Curie</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2012</debut>
            <fin>2021</fin>
            <entreprise>Libérale</entreprise>
            <poste>Médecin-Généraliste</poste>
        </experience>
        <experience>
            <debut>2021</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Généraliste</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Ratiffe</nom>
        <prenom>Luc</prenom>
        <age>1970</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>1990</annee>
            <institution>Université de Nantes</institution>
        </diplome>
        <diplome>
            <libelle>Spécialisation en Dermatologie</libelle>
            <annee>1995</annee>
            <institution>Université de Nantes</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>1996</debut>
            <fin>2013</fin>
            <entreprise>Etat Français</entreprise>
            <poste>Médécin-Dermatologue</poste>
        </experience>
        <experience>
            <debut>2013</debut>
            <fin>Présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médécin-Dermatologue</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Iléausud</nom>
        <prenom>Eléonore</prenom>
        <age>1965</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteure en médecine</libelle>
            <annee>1980</annee>
            <institution>Université de Lille 2</institution>
        </diplome>
        <diplome>
            <libelle>Diplôme en pédiatrie</libelle>
            <annee>1985</annee>
            <institution>Université de Lille 2</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2000</debut>
            <fin>2016</fin>
            <entreprise>Libérale</entreprise>
            <poste>Médecin-Pédiatre</poste>
        </experience>
        <experience>
            <debut>2016</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Généraliste et pédiatrique</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Tuission</nom>
        <prenom>Alain</prenom>
        <age>1968</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>1988</annee>
            <institution>Université Sorbonne</institution>
        </diplome>
        <diplome>
            <libelle>Diplome d'études spécialisées Cardiologie et Maldies vasculaires</libelle>
            <annee>2000</annee>
            <institution>Paris Saclay</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2007</debut>
            <fin>2018</fin>
            <entreprise>Georges Pompidou</entreprise>
            <poste>Medecin-Cardiologue</poste>
        </experience>
        <experience>
            <debut>2018</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Medecin-Cardiologue</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Ergébel</nom>
        <prenom>Octave</prenom>
        <age>1971</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en Médecine</libelle>
            <annee>1999</annee>
            <institution>Université Paris-Diderot</institution>
        </diplome>
        <diplome>
            <libelle>Docteur d'andrologie</libelle>
            <annee>1995</annee>
            <institution>Université Paris-Diderot</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2000</debut>
            <fin>2011</fin>
            <entreprise>Hopital Foch</entreprise>
            <poste>Medecin-Andrologue</poste>
        </experience>
        <experience>
            <debut>2011</debut>
            <fin>2019</fin>
            <entreprise>Hopital Américain de Neuilly-Sur-Seine</entreprise>
            <poste>Medecin-Andrologue</poste>
        </experience>
        <experience>
            <debut>2019</debut>
            <fin>Présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Medecin-Andrologue</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Rines</nom>
        <prenom>Léna</prenom>
        <age>1991</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>2005</annee>
            <institution>Université Aix-Marseille</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2020</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Généraliste</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Chon</nom>
        <prenom>Dénis</prenom>
        <age>1979</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>2003</annee>
            <institution>Université Paris Descartes</institution>
        </diplome>
        <diplome>
            <libelle>Spécialisation Gynécologique-obstétrique</libelle>
            <annee>2007</annee>
            <institution>Université Paris Descartes</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2008</debut>
            <fin>2017</fin>
            <entreprise>Maternité chu Rouen</entreprise>
            <poste>Gynécologue-obstétricien </poste>
        </experience>
        <experience>
            <debut>2017</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Gynécologue-obstétricien </poste>
        </experience>
    </experiences>
</cv>
