=== Ahddry/PiscineWeb2022/XML/template.dtd
<!ELEMENT cv (etatCivil,diplomes,experiences)>

<!ELEMENT etatCivil (nom , prenom, age)>

<!ELEMENT diplomes (diplome+)>
<!ELEMENT diplome (libelle , annee, institution)>

<!ELEMENT experiences (experience+)>
<!ELEMENT experience (debut , fin, entreprise, poste)>


<!ELEMENT nom (#PCDATA )>
<!ELEMENT prenom (#PCDATA )>
<!ELEMENT age (#PCDATA )>

<!ELEMENT libelle (#PCDATA )>
<!ELEMENT annee (#PCDATA )>
<!ELEMENT institution (#PCDATA )>

<!ELEMENT debut (#PCDATA )>
<!ELEMENT fin (#PCDATA )>
<!ELEMENT entreprise (#PCDATA )>
<!ELEMENT poste (#PCDATA )>

=== Ahddry/PiscineWeb2022/XML/8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Pyration</nom>
        <prenom>Alex</prenom>
        <age>1975</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Diplomée en Ostéopathie</libelle>
            <annee>1990</annee>
            <institution>Ostéopathie de Paris</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>1998</debut>
            <fin>2020</fin>
            <entreprise>Libéral</entreprise>
            <poste>Ostéopathe</poste>
        </experience>
        <experience>
            <debut>2020</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Osthéopathe</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom></nom>
        <prenom></prenom>
        <age></age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle></libelle>
            <annee></annee>
            <institution></institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut></debut>
            <fin></fin>
            <entreprise></entreprise>
            <poste></poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Faimal</nom>
        <prenom>Aicha</prenom>
        <age>1994</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Diplômée de L'IFSI</libelle>
            <annee>2010</annee>
            <institution>CH de Soisson</institution>
        </diplome>
        <diplome>
            <libelle>Spécialisation en santé du travail</libelle>
            <annee>2012</annee>
            <institution>CH de Soisson</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2015</debut>
            <fin>2019</fin>
            <entreprise>Groupe Bruneau</entreprise>
            <poste>Infirmière en santé du travail </poste>
        </experience>
        <experience>
            <debut>2019</debut>
            <fin>Présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Infirmière en santé du travail </poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Lavaithonku</nom>
        <prenom>Eva</prenom>
        <age>1989</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>2001</annee>
            <institution>Université Toulouse 3</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2018</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Généraliste</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Tommye</nom>
        <prenom>Anna</prenom>
        <age>1986</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en Médecine</libelle>
            <annee>1990</annee>
            <institution>Université Partis Diderot</institution>
        </diplome>
        <diplome>
            <libelle>Spécialisation Gastro-entérologie et hépatologie</libelle>
            <annee>1995</annee>
            <institution>Université Partis Diderot</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2018</debut>
            <fin>2020</fin>
            <entreprise>CHU Pitié-Salpêtrière</entreprise>
            <poste>Gastro-Hépato-Entérologue</poste>
        </experience>
        <experience>
            <debut>2020</debut>
            <fin>Présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Gastro-Hépato-Entérologue</poste>
        </experience>
    </experiences>
</cv>

=== Ahddry/PiscineWeb2022/XML/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "template.dtd">
<cv>
    <etatCivil>
        <nom>Remor</nom>
        <prenom>Yves</prenom>
        <age>1986</age>
    </etatCivil>
    <diplomes>
        <diplome>
            <libelle>Docteur en médecine</libelle>
            <annee>2000</annee>
            <institution>Université Paris-Saclay</institution>
        </diplome>
        <diplome>
            <libelle>Diplome Universitaire en addictologie</libelle>
            <annee>1997</annee>
            <institution>Université de Caen</institution>
        </diplome>
        <diplome>
            <libelle>Cours Psycologie anti-drogue</libelle>
            <annee>2017</annee>
            <institution>e-learning</institution>
        </diplome>
    </diplomes>
    <experiences>
        <experience>
            <debut>2015</debut>
            <fin>présent</fin>
            <entreprise>Omnes Santé</entreprise>
            <poste>Médecin-Addictologue</poste>
        </experience>
    </experiences>
</cv>
